# Variables
resourceGroup="acdnd-c4-project"
location="southeastasia"
osType="Ubuntu2204"
vmssName="udacity-vmss"
adminName="udacityadmin"
bePoolName="$vmssName-bepool"
lbName="$vmssName-lb"
lbRule="$lbName-network-rule"
nsgName="$vmssName-nsg"
vnetName="$vmssName-vnet"
subnetName="$vnetName-subnet"
probeName="tcpProbe"
vmSize="Standard_B1s"
storageType="Standard_LRS"
orchestrationMode="Uniform"